# Generated by Django 5.2.7 on 2025-11-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='ДатаВремя добавления')),
                ('path', models.CharField(max_length=254, verbose_name='Метод получения')),
                ('user_agent', models.CharField(blank=True, max_length=254, null=True, verbose_name='User Agent отправителя')),
                ('ip_adr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес отправителя')),
                ('parsed_query', models.JSONField(blank=True, null=True, verbose_name='Разобранные параметры запроса')),
                ('data', models.TextField(verbose_name='Тело запроса')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('error', 'Ошибка'), ('complete', 'Завершено')], default='new', max_length=20, verbose_name='Статус обработки')),
                ('error_description', models.TextField(blank=True, null=True, verbose_name='Текст ошибки')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='ДатаВремя обработки')),
            ],
            options={
                'verbose_name': 'Входящее уведомление',
                'verbose_name_plural': 'Входящие уведомления',
                'ordering': ['-inserted_at'],
            },
        ),
    ]
