# Generated by Django 5.2.7 on 2025-11-04 13:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookrequest',
            name='content_type',
            field=models.CharField(default='', max_length=254, verbose_name='Контент в заголовках'),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='full_url',
            field=models.URLField(default='', max_length=500, verbose_name='Полная строка вызова'),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='request_method',
            field=models.CharField(default='POST', max_length=10, verbose_name='HTTP метод запроса'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='data',
            field=models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Тело запроса'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='error_description',
            field=models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='ip_adr',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4', verbose_name='IP адрес отправителя'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='parsed_query',
            field=models.JSONField(default=dict, verbose_name='Разобранные параметры запроса'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='path',
            field=models.CharField(default='', max_length=254, verbose_name='Точка вызова'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='processed_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='ДатаВремя обработки'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='user_agent',
            field=models.CharField(default='', max_length=254, verbose_name='User Agent отправителя'),
        ),
        migrations.AddIndex(
            model_name='webhookrequest',
            index=models.Index(fields=['status', 'inserted_at'], name='main_wh_web_status_12bbc3_idx'),
        ),
    ]
