# Generated by Django 5.2.7 on 2025-11-05 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wh', '0002_webhookrequest_content_type_webhookrequest_full_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookrequest',
            name='full_url',
            field=models.URLField(default='', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Полная строка вызова'),
        ),
        migrations.AddIndex(
            model_name='webhookrequest',
            index=models.Index(fields=['processed_at'], name='main_wh_web_process_2098da_idx'),
        ),
    ]
