# Generated by Django 5.2.7 on 2025-11-05 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wh', '0003_alter_webhookrequest_full_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookrequest',
            name='data',
            field=models.TextField(default='', max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Тело запроса'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='error_description',
            field=models.TextField(default='', max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Текст ошибки'),
        ),
    ]
