# Generated by Django 5.2.7 on 2025-11-06 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wh', '0004_alter_webhookrequest_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookrequest',
            name='parsed_query',
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='parsed_body',
            field=models.JSONField(default=dict, max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Преобразованные данные'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='data',
            field=models.TextField(default='', max_length=5000, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Сырые данные'),
        ),
    ]
