# Generated by Django 5.2.7 on 2025-11-22 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wh', '0005_remove_webhookrequest_parsed_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookrequest',
            name='data',
            field=models.TextField(default='', max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='webhookrequest',
            name='parsed_body',
            field=models.JSONField(default=dict, max_length=10000, validators=[django.core.validators.MaxLengthValidator(10000)], verbose_name='Преобразованные данные'),
        ),
        migrations.CreateModel(
            name='CategoryWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ext', models.CharField(max_length=32, unique=True, verbose_name='Внешний идентификатор')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(default='', max_length=500, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория Уведомления',
                'verbose_name_plural': 'Категории Уведомлений',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id_ext', 'is_active'], name='main_wh_cat_id_ext_faca52_idx')],
            },
        ),
    ]
