# Generated by Django 5.2.7 on 2025-12-08 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_wh', '0007_category_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookrequest',
            name='business_processed_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата обработки бизнес-логикой'),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='business_queued_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки в бизнес-очередь'),
        ),
        migrations.AddField(
            model_name='webhookrequest',
            name='business_status',
            field=models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('complete', 'Обработано'), ('failed', 'Ошибка обработки')], default='pending', max_length=20, verbose_name='Статус бизнес-обработки'),
        ),
        migrations.AddIndex(
            model_name='webhookrequest',
            index=models.Index(fields=['business_status', 'business_queued_at'], name='main_wh_web_busines_0592d4_idx'),
        ),
    ]
